---
label: Project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Project Title
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: Short project description goes here
- name: hero_background_color
  type: color
  label: Hero Background Color
  config:
    required: true
    color_format: Hex
- name: year
  type: number
  label: Year
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
- name: category
  type: select
  default: []
  config:
    required: true
    options:
    - Branding
    - Interaction
    - Motion
    - Print
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
- name: content
  type: blocks
  label: Content
  template_types: []
  config:
    min: 1
    max: 
